//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 xsd 自动生成, Version=4.6.81.0。
// 
namespace JenkinsBuild {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Icon {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string explain;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class PCAndIOS {
        
        /// <remarks/>
        public int Build;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BuildSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AndroidAndIOS {
        
        /// <remarks/>
        public UIOrientationEnum DefaultOrientation;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DefaultOrientationSpecified;
        
        /// <remarks/>
        public bool Portrait;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PortraitSpecified;
        
        /// <remarks/>
        public bool PortraitUpsideDown;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PortraitUpsideDownSpecified;
        
        /// <remarks/>
        public bool LandscapeRight;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LandscapeRightSpecified;
        
        /// <remarks/>
        public bool LandscapeLeft;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LandscapeLeftSpecified;
        
        /// <remarks/>
        public bool DisableDepthAndStencil;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DisableDepthAndStencilSpecified;
        
        /// <remarks/>
        public bool MuteOtherAudioSources;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MuteOtherAudioSourcesSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    public enum UIOrientationEnum {
        
        /// <remarks/>
        Portrait,
        
        /// <remarks/>
        PortraitUpsideDown,
        
        /// <remarks/>
        LandscapeRight,
        
        /// <remarks/>
        LandscapeLeft,
        
        /// <remarks/>
        AutoRotation,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class BuildInfo {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Scence", IsNullable=false)]
        public BuildInfoScence[] Scences;
        
        /// <remarks/>
        // CODEGEN 警告: 此版本的 .Net Framework 不支持 BuildInfoCompanyName 类型成员的 DefaultValue 特性。
        // CODEGEN 警告: 只有基元类型支持“default”特性。忽略 default='DefaultCompany' 特性。
        public BuildInfoCompanyName CompanyName;
        
        /// <remarks/>
        // CODEGEN 警告: 此版本的 .Net Framework 不支持 BuildInfoProductName 类型成员的 DefaultValue 特性。
        // CODEGEN 警告: 只有基元类型支持“default”特性。忽略 default='DefaultProduct' 特性。
        public BuildInfoProductName ProductName;
        
        /// <remarks/>
        public BuildInfoCursorHotspot CursorHotspot;
        
        /// <remarks/>
        public BuildInfoIcons Icons;
        
        /// <remarks/>
        public ColorSpaceEnum ColorSpace;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ColorSpaceSpecified;
        
        /// <remarks/>
        // CODEGEN 警告: 此版本的 .Net Framework 不支持 BuildInfoAutoGraphicsAPI 类型成员的 DefaultValue 特性。
        // CODEGEN 警告: 只有基元类型支持“default”特性。忽略 default='true' 特性。
        public BuildInfoAutoGraphicsAPI AutoGraphicsAPI;
        
        /// <remarks/>
        // CODEGEN 警告: 此版本的 .Net Framework 不支持 BuildInfoStaticBatching 类型成员的 DefaultValue 特性。
        // CODEGEN 警告: 只有基元类型支持“default”特性。忽略 default='true' 特性。
        public BuildInfoStaticBatching StaticBatching;
        
        /// <remarks/>
        // CODEGEN 警告: 此版本的 .Net Framework 不支持 BuildInfoDynamicBatching 类型成员的 DefaultValue 特性。
        // CODEGEN 警告: 只有基元类型支持“default”特性。忽略 default='true' 特性。
        public BuildInfoDynamicBatching DynamicBatching;
        
        /// <remarks/>
        public BuildInfoGPUSkinning GPUSkinning;
        
        /// <remarks/>
        public BuildInfoGraphicsJobs GraphicsJobs;
        
        /// <remarks/>
        public BuildInfoVitualRealitySupported VitualRealitySupported;
        
        /// <remarks/>
        public BuildInfoVersion Version;
        
        /// <remarks/>
        public ScriptingImplementationEnum ScriptingBackend;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ScriptingBackendSpecified;
        
        /// <remarks/>
        public ApiCompatibilityLevelEnum APICompatibilityLevel;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool APICompatibilityLevelSpecified;
        
        /// <remarks/>
        public BuildInfoScriptingDefineSymbols ScriptingDefineSymbols;
        
        /// <remarks/>
        public BuildInfoPrebakeCollisionMeshes PrebakeCollisionMeshes;
        
        /// <remarks/>
        public BuildInfoKeepLoadedShadersAlive KeepLoadedShadersAlive;
        
        /// <remarks/>
        public StrippingLevelEnum StrippingLevel;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StrippingLevelSpecified;
        
        /// <remarks/>
        public BuildInfoEnableInternalProfiler EnableInternalProfiler;
        
        /// <remarks/>
        public BuildInfoOptimizeMeshData OptimizeMeshData;
        
        /// <remarks/>
        public BuildInfoLogging Logging;
        
        /// <remarks/>
        public BuildInfoBuildType BuildType;
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Development;
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ConnectProfiler;
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ScriptsDebuggers;
        
        /// <remarks/>
        public string OutPath;
        
        /// <remarks/>
        public string PackNname;
        
        public BuildInfo() {
            this.Development = false;
            this.ConnectProfiler = false;
            this.ScriptsDebuggers = false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoScence {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string explain;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoCompanyName {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoProductName {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoCursorHotspot {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoIcons {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Android", typeof(BuildInfoIconsAndroid))]
        [System.Xml.Serialization.XmlElementAttribute("IOS", typeof(BuildInfoIconsIOS))]
        [System.Xml.Serialization.XmlElementAttribute("PC", typeof(BuildInfoIconsPC))]
        public object Item;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoIconsAndroid {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Icon")]
        public Icon[] Icon;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoIconsIOS {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Icon")]
        public Icon[] Icon;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoIconsPC {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Icon")]
        public Icon[] Icon;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    public enum ColorSpaceEnum {
        
        /// <remarks/>
        Gamma,
        
        /// <remarks/>
        Uninitialized,
        
        /// <remarks/>
        Linear,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoAutoGraphicsAPI {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoStaticBatching {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoDynamicBatching {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoGPUSkinning {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoGraphicsJobs {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoVitualRealitySupported {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoVersion {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    public enum ScriptingImplementationEnum {
        
        /// <remarks/>
        Mono2x,
        
        /// <remarks/>
        IL2CPP,
        
        /// <remarks/>
        WinRTDotNET,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    public enum ApiCompatibilityLevelEnum {
        
        /// <remarks/>
        NET_2_0_Subset,
        
        /// <remarks/>
        NET_2_0,
        
        /// <remarks/>
        NET_4_6,
        
        /// <remarks/>
        NET_Web,
        
        /// <remarks/>
        NET_Micro,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoScriptingDefineSymbols {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool IsAdd;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
        
        public BuildInfoScriptingDefineSymbols() {
            this.IsAdd = true;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoPrebakeCollisionMeshes {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoKeepLoadedShadersAlive {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    public enum StrippingLevelEnum {
        
        /// <remarks/>
        Disabled,
        
        /// <remarks/>
        StripAssemblies,
        
        /// <remarks/>
        StripByteCode,
        
        /// <remarks/>
        UseMicroMSCorlib,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoEnableInternalProfiler {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoOptimizeMeshData {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoLogging {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Type")]
        public BuildInfoLoggingType[] Type;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoLoggingType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StackTraceLogTypeEnum StackType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StackTypeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public LogTypeEnum Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    public enum StackTraceLogTypeEnum {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        ScriptOnly,
        
        /// <remarks/>
        Full,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    public enum LogTypeEnum {
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Assert,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Log,
        
        /// <remarks/>
        Exception,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Android", typeof(BuildInfoBuildTypeAndroid))]
        [System.Xml.Serialization.XmlElementAttribute("IOS", typeof(BuildInfoBuildTypeIOS))]
        [System.Xml.Serialization.XmlElementAttribute("PC", typeof(BuildInfoBuildTypePC))]
        public object Item;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypeAndroid {
        
        /// <remarks/>
        public AndroidAndIOS AndroidAndIOS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Use32-bitDisplayBuffer")]
        public BuildInfoBuildTypeAndroidUse32bitDisplayBuffer Use32bitDisplayBuffer;
        
        /// <remarks/>
        public BuildInfoBuildTypeAndroidProtectGraphicsMemory ProtectGraphicsMemory;
        
        /// <remarks/>
        public BuildInfoBuildTypeAndroidBundleVersionCode BundleVersionCode;
        
        /// <remarks/>
        public int MinimumAPILevel;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinimumAPILevelSpecified;
        
        /// <remarks/>
        public int TargetAPILevel;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TargetAPILevelSpecified;
        
        /// <remarks/>
        public AndroidShowActivityIndicatorOnLoadingEnum ShowLoadingIndicator;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShowLoadingIndicatorSpecified;
        
        /// <remarks/>
        public AndroidTargetDeviceEnum DeveiceFilter;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeveiceFilterSpecified;
        
        /// <remarks/>
        public AndroidPreferredInstallLocationEnum InstallLocation;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InstallLocationSpecified;
        
        /// <remarks/>
        public bool InternetAccess;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InternetAccessSpecified;
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool WriteSDCard;
        
        /// <remarks/>
        public BuildInfoBuildTypeAndroidAndroidTVCompatibility AndroidTVCompatibility;
        
        /// <remarks/>
        public BuildInfoBuildTypeAndroidAndroidGame AndroidGame;
        
        /// <remarks/>
        public AndroidBuildSystemEnum BuildSystem;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BuildSystemSpecified;
        
        /// <remarks/>
        public MobileTextureSubtargetEnum BuildSubtarget;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BuildSubtargetSpecified;
        
        /// <remarks/>
        public AndroidETC2FallbackEnum ETC2Fallback;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ETC2FallbackSpecified;
        
        public BuildInfoBuildTypeAndroid() {
            this.WriteSDCard = true;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypeAndroidUse32bitDisplayBuffer {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypeAndroidProtectGraphicsMemory {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypeAndroidBundleVersionCode {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public int Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    public enum AndroidShowActivityIndicatorOnLoadingEnum {
        
        /// <remarks/>
        DontShow,
        
        /// <remarks/>
        Large,
        
        /// <remarks/>
        InversedLarge,
        
        /// <remarks/>
        Small,
        
        /// <remarks/>
        InversedSmall,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    public enum AndroidTargetDeviceEnum {
        
        /// <remarks/>
        FAT,
        
        /// <remarks/>
        ARMv7,
        
        /// <remarks/>
        x86,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    public enum AndroidPreferredInstallLocationEnum {
        
        /// <remarks/>
        Auto,
        
        /// <remarks/>
        PreferExternal,
        
        /// <remarks/>
        ForceInternal,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypeAndroidAndroidTVCompatibility {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypeAndroidAndroidGame {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    public enum AndroidBuildSystemEnum {
        
        /// <remarks/>
        Internal,
        
        /// <remarks/>
        Gradle,
        
        /// <remarks/>
        ADT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    public enum MobileTextureSubtargetEnum {
        
        /// <remarks/>
        Generic,
        
        /// <remarks/>
        DXT,
        
        /// <remarks/>
        PVRTC,
        
        /// <remarks/>
        ATC,
        
        /// <remarks/>
        ETC,
        
        /// <remarks/>
        ETC2,
        
        /// <remarks/>
        ASTC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    public enum AndroidETC2FallbackEnum {
        
        /// <remarks/>
        Quality32Bit,
        
        /// <remarks/>
        Quality16Bit,
        
        /// <remarks/>
        Quality32BitDownscaled,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypeIOS {
        
        /// <remarks/>
        public PCAndIOS PCAndIOS;
        
        /// <remarks/>
        public AndroidAndIOS AndroidAndIOS;
        
        /// <remarks/>
        public BuildInfoBuildTypeIOSUseAnimatedAutorotation UseAnimatedAutorotation;
        
        /// <remarks/>
        public BuildInfoBuildTypeIOSRequiresFullscreen RequiresFullscreen;
        
        /// <remarks/>
        public BuildInfoBuildTypeIOSStatusBarHidden StatusBarHidden;
        
        /// <remarks/>
        // CODEGEN 警告: 此版本的 .Net Framework 不支持 BuildInfoBuildTypeIOSAutomaticallySign 类型成员的 DefaultValue 特性。
        // CODEGEN 警告: 只有基元类型支持“default”特性。忽略 default='true' 特性。
        public BuildInfoBuildTypeIOSAutomaticallySign AutomaticallySign;
        
        /// <remarks/>
        public BuildInfoBuildTypeIOSUseOnDemandResources UseOnDemandResources;
        
        /// <remarks/>
        public BuildInfoBuildTypeIOSPrepareIOSForRecording PrepareIOSForRecording;
        
        /// <remarks/>
        public BuildInfoBuildTypeIOSRequiresPersistentWifi RequiresPersistentWifi;
        
        /// <remarks/>
        // CODEGEN 警告: 此版本的 .Net Framework 不支持 BuildInfoBuildTypeIOSAllowDownloadsOverHttp 类型成员的 DefaultValue 特性。
        // CODEGEN 警告: 只有基元类型支持“default”特性。忽略 default='true' 特性。
        public BuildInfoBuildTypeIOSAllowDownloadsOverHttp AllowDownloadsOverHttp;
        
        /// <remarks/>
        public BuildInfoBuildTypeIOSRenderExtraFrameOnPause RenderExtraFrameOnPause;
        
        /// <remarks/>
        public BuildInfoBuildTypeIOSDisableHWStatistics DisableHWStatistics;
        
        /// <remarks/>
        public BuildInfoBuildTypeIOSAutomaticSigningTeamID AutomaticSigningTeamID;
        
        /// <remarks/>
        public string TargetMinimumIOSVersion;
        
        /// <remarks/>
        public BuildInfoBuildTypeIOSCameraUsageDescription CameraUsageDescription;
        
        /// <remarks/>
        public BuildInfoBuildTypeIOSLocationUsageDescription LocationUsageDescription;
        
        /// <remarks/>
        public BuildInfoBuildTypeIOSMicrophoneUsageDescription MicrophoneUsageDescription;
        
        /// <remarks/>
        public IOSStatusBarStyleEnum StatusBarStyle;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusBarStyleSpecified;
        
        /// <remarks/>
        public IOSTargetDeviceEnum TargetDevice;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TargetDeviceSpecified;
        
        /// <remarks/>
        public IOSSdkVersionEnum TargetSdK;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TargetSdKSpecified;
        
        /// <remarks/>
        public int AccelerometerFrequency;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccelerometerFrequencySpecified;
        
        /// <remarks/>
        public IOSAppInBackgroundBehaviorEnum BehaviorInBackground;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BehaviorInBackgroundSpecified;
        
        /// <remarks/>
        public int Architecture;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ArchitectureSpecified;
        
        /// <remarks/>
        public IOSShowActivityIndicatorOnLoadingEnum ShowLoadingIndicator;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShowLoadingIndicatorSpecified;
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ForcehardShadowsOnMetal;
        
        public BuildInfoBuildTypeIOS() {
            this.ForcehardShadowsOnMetal = false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypeIOSUseAnimatedAutorotation {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypeIOSRequiresFullscreen {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypeIOSStatusBarHidden {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypeIOSAutomaticallySign {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypeIOSUseOnDemandResources {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypeIOSPrepareIOSForRecording {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypeIOSRequiresPersistentWifi {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypeIOSAllowDownloadsOverHttp {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypeIOSRenderExtraFrameOnPause {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypeIOSDisableHWStatistics {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypeIOSAutomaticSigningTeamID {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypeIOSCameraUsageDescription {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypeIOSLocationUsageDescription {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypeIOSMicrophoneUsageDescription {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    public enum IOSStatusBarStyleEnum {
        
        /// <remarks/>
        BlackTranslucent,
        
        /// <remarks/>
        BlackOpaque,
        
        /// <remarks/>
        Default,
        
        /// <remarks/>
        LightContent,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    public enum IOSTargetDeviceEnum {
        
        /// <remarks/>
        iPhoneAndiPad,
        
        /// <remarks/>
        iPhoneOnly,
        
        /// <remarks/>
        iPadOnly,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    public enum IOSSdkVersionEnum {
        
        /// <remarks/>
        DeviceSDK,
        
        /// <remarks/>
        SimulatorSDK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    public enum IOSAppInBackgroundBehaviorEnum {
        
        /// <remarks/>
        Custom,
        
        /// <remarks/>
        Suspend,
        
        /// <remarks/>
        Exit,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    public enum IOSShowActivityIndicatorOnLoadingEnum {
        
        /// <remarks/>
        DontShow,
        
        /// <remarks/>
        WhiteLarge,
        
        /// <remarks/>
        White,
        
        /// <remarks/>
        Gray,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypePC {
        
        /// <remarks/>
        public PCAndIOS PCAndIOS;
        
        /// <remarks/>
        public BuildInfoBuildTypePCDefaultIsFullScreen DefaultIsFullScreen;
        
        /// <remarks/>
        public BuildInfoBuildTypePCDefaultIsNativeResolution DefaultIsNativeResolution;
        
        /// <remarks/>
        public BuildInfoBuildTypePCRunInBackground RunInBackground;
        
        /// <remarks/>
        public BuildInfoBuildTypePCCaptureSingleScreen CaptureSingleScreen;
        
        /// <remarks/>
        public BuildInfoBuildTypePCUsePlayerLog UsePlayerLog;
        
        /// <remarks/>
        public BuildInfoBuildTypePCResizableWindow ResizableWindow;
        
        /// <remarks/>
        public BuildInfoBuildTypePCVisibleInBackground VisibleInBackground;
        
        /// <remarks/>
        public BuildInfoBuildTypePCAllowFullscreenSwitch AllowFullscreenSwitch;
        
        /// <remarks/>
        public BuildInfoBuildTypePCForceSingleInstance ForceSingleInstance;
        
        /// <remarks/>
        public BuildInfoBuildTypePCMacAppStoreValidation MacAppStoreValidation;
        
        /// <remarks/>
        public ResolutionDialogSettingEnum DisplayResolutionDialog;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DisplayResolutionDialogSpecified;
        
        /// <remarks/>
        public MacFullscreenModeEnum MacFullscreenMode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MacFullscreenModeSpecified;
        
        /// <remarks/>
        public D3D9FullscreenModeEnum D3D9FullscreenMode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool D3D9FullscreenModeSpecified;
        
        /// <remarks/>
        public D3D11FullscreenModeEnum D3D11FullscreenMode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool D3D11FullscreenModeSpecified;
        
        /// <remarks/>
        public BuildInfoBuildTypePCSupportedAspectRations SupportedAspectRations;
        
        /// <remarks/>
        public string Category;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypePCDefaultIsFullScreen {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypePCDefaultIsNativeResolution {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypePCRunInBackground {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypePCCaptureSingleScreen {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypePCUsePlayerLog {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypePCResizableWindow {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypePCVisibleInBackground {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypePCAllowFullscreenSwitch {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypePCForceSingleInstance {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypePCMacAppStoreValidation {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    public enum ResolutionDialogSettingEnum {
        
        /// <remarks/>
        Disabled,
        
        /// <remarks/>
        Enabled,
        
        /// <remarks/>
        HiddenByDefault,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    public enum MacFullscreenModeEnum {
        
        /// <remarks/>
        CaptureDisplay,
        
        /// <remarks/>
        FullscreenWindow,
        
        /// <remarks/>
        FullscreenWindowWithDockAndMenuBar,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    public enum D3D9FullscreenModeEnum {
        
        /// <remarks/>
        ExclusiveMode,
        
        /// <remarks/>
        FullscreenWindow,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    public enum D3D11FullscreenModeEnum {
        
        /// <remarks/>
        ExclusiveMode,
        
        /// <remarks/>
        FullscreenWindow,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypePCSupportedAspectRations {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AspectRatio")]
        public BuildInfoBuildTypePCSupportedAspectRationsAspectRatio[] AspectRatio;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BuildInfoBuildTypePCSupportedAspectRationsAspectRatio {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool enable;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enableSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public AspectRatioEnum Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    public enum AspectRatioEnum {
        
        /// <remarks/>
        AspectOthers,
        
        /// <remarks/>
        Aspect4by3,
        
        /// <remarks/>
        Aspect5by4,
        
        /// <remarks/>
        Aspect16by10,
        
        /// <remarks/>
        Aspect16by9,
    }
}
